### PR TITLE
Updates to CEP27

### PR DESCRIPTION
**Pull request by scopatz**
Hi @jbae11 - Here are some proposed edits to CEP27.  Merge if you agree, comment if you don't! :)

### CODE REVIEW

**Comment by jbae11** [comment]
Looks awesome! Sorry for the petty mistakes :/

**Comment by scopatz** [comment]
No worries! It is important to be particular here :)

**Comment by jbae11** [comment]
@scopatz  So what's the next step? Is it ready to be a PR to the cyclus/cyclus.github.com?

**Comment by scopatz** [comment]
I am happy with it, if you are happy with it.  The next step is to PR it into the mainline repo, as you say.  Then also send it to cyclus-dev@googlegroups.com for discussion

**Pull request merged**
